collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6240838
  brandStrength: 0.3870832
  lightness: 0
  brandColors:
    - '#919088'
    - '#BEBDB4'
    - '#151515'
    - '#E9EAE8'
    - '#5B9131'
  rhythmicContrast: 0.03173597
typography_spectrum: 0.09677419
layout_spectrum: 0
name: To be yourself
