layout_spectrum: 0.03889049
typography_spectrum: 0.5292652
color:
  saturation: 0.6240838
  lightness: 0.9225217
  brandStrength: 0.3870832
  rhythmicContrast: 0.03173597
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: To be yourself
